containers:
  core:
    capAdd:
      - ALL
    disableInit: true
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    hostIPC: true
    hostUTS: true
    hostNetwork: true
    image: skiffos/skiff-core-linux4tegra:latest
    mounts:
      - /dev:/dev
      - /lib/modules:/lib/modules
      - /mnt/persist/nvidia-docker:/var/lib/docker
      - /mnt:/mnt
      - /run/udev:/run/udev
      - /home/.ecryptfs:/mnt/persist/skiff/core/ecryptfs
    privileged: true
    restartPolicy: "always"
    securityOpt:
      - seccomp=unconfined
    startAfterCreate: true
    tty: true
    workingDirectory: /home/nvidia
users:
  nvidia:
    container: core
    containerUser: nvidia
    containerShell:
      - "/bin/bash"
    auth:
      copyRootKeys: true
images:
  skiffos/skiff-core-linux4tegra:latest:
    build:
      source: /opt/skiff/coreenv/skiff-core-linux4tegra
      squash: true
