containers:
  core:
    image: skiffos/skiff-core-linux4tegra:latest
    tty: true
    disableInit: true
    workingDirectory: /home/nvidia
    mounts:
      - /dev:/dev
      - /lib/modules:/lib/modules
      - /mnt/persist/nvidia-docker:/var/lib/docker
      - /mnt:/mnt
      - /run/udev:/run/udev
      - /home/.ecryptfs:/mnt/persist/skiff/core/ecryptfs
      - /etc/nv_tegra_release:/etc/nv_tegra_release
      - /etc/vulkan:/etc/vulkan
      - /var/nvidia/nvcam:/var/nvidia/nvcam
      - /usr/bin/nvidia-bug-report-tegra.sh:/usr/bin/nvidia-bug-report-tegra.sh
      - /usr/sbin/nvargus-daemon:/usr/sbin/nvargus-daemon
      - /usr/sbin/nvphsd:/usr/sbin/nvphsd
      - /usr/sbin/nvs-service:/usr/sbin/nvs-service
      - /usr/sbin/nvtunerd:/usr/sbin/nvtunerd
      - /usr/share/doc/nvidia-tegra:/usr/share/doc/nvidia-tegra
      - /usr/share/egl:/usr/share/egl
      - /usr/share/glvnd:/usr/share/glvnd
      - /usr/lib/aarch64-linux-gnu/libdrm_nvdc.so:/usr/lib/aarch64-linux-gnu/libdrm_nvdc.so
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra
      - /usr/lib/aarch64-linux-gnu/tegra-egl:/usr/lib/aarch64-linux-gnu/tegra-egl
      - /usr/lib/aarch64-linux-gnu/libv4l2.so.0.0.999999:/usr/lib/aarch64-linux-gnu/libv4l2.so.0.0.999999
      - /usr/lib/aarch64-linux-gnu/libv4lconvert.so.0.0.999999:/usr/lib/aarch64-linux-gnu/libv4lconvert.so.0.0.999999
      - /usr/lib/aarch64-linux-gnu/libvulkan.so.1.2:/usr/lib/aarch64-linux-gnu/libvulkan.so.1.2
      - /usr/lib/aarch64-linux-gnu/libv4l/plugins/nv:/usr/lib/aarch64-linux-gnu/libv4l/plugins/nv
      - /usr/lib/tegra:/usr/lib/tegra
      - /usr/lib/xorg/modules/drivers/nvidia_drv.so:/usr/lib/xorg/modules/drivers/nvidia_drv.so
      - /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so:/usr/lib/xorg/modules/extensions/libglxserver_nvidia.so
    privileged: true
    restartPolicy: "always"
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    capAdd:
      - ALL
    hostIPC: true
    hostUTS: true
    hostNetwork: true
    securityOpt:
      - seccomp=unconfined
users:
  nvidia:
    container: core
    containerUser: nvidia
    containerShell:
      - "/bin/bash"
    auth:
      copyRootKeys: true
images:
  skiffos/skiff-core-linux4tegra:latest:
    build:
      source: /opt/skiff/coreenv/skiff-core-linux4tegra
      dockerfile: COREENV_DOCKERFILE
      squash: true
