name: CI

# Controls when the action will run.
on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks
    steps:
      # Checks-out the repo under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Cache build cache and downloads
        uses: actions/cache@v2
        env:
          cache-name: cache-buildroot
        with:
          path: ~/br-cache/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Installing buildroot deps
      - name: Install buildroot apt deps
        run: |
          sudo apt-get install -y libelf-dev

      # Print help
      - name: Print help and packages list
        run: |
          cd $GITHUB_WORKSPACE
          make help

      # Test a build
      - name: Build a Docker container image
        run: |
          cd $GITHUB_WORKSPACE
          export TERM=xterm
          export BR2_CCACHE_DIR=${HOME}/br-cache/ccache
          export BR2_DL_DIR=${HOME}/br-cache/dl
          export SKIFF_WORKSPACE=docker
          export SKIFF_CONFIG=virt/docker,skiff/core,util/gofast
          make -s configure check compile
          echo "Compilation complete, building Docker image..."
          make cmd/virt/docker/buildimage
          mkdir -p workflow-artifacts
          docker save paralin/skiffos:latest | gzip -9 > ./workflow-artifacts/docker-image.tar.gz

      # Upload docker image
      - uses: actions/upload-artifact@v2
        with:	
          name: docker-image.tar.gz
          path: ${{ github.workspace }}/workflow-artifacts/docker-image.tar.gz

